# Generated by Django 5.0.6 on 2024-07-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='provider',
            field=models.CharField(choices=[('local', 'local'), ('google', 'google')], default='local', max_length=255),
        ),
    ]
